<a href="https://colab.research.google.com/github/Inryu/capstone-design-exception/blob/main/deep-learning/3_5_%EC%B6%9C%EB%A0%A5%EC%B8%B5_%EC%84%A4%EA%B3%84%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## __3.5 출력층 설계하기__

### __3.5.1 항등 함수와 소프트맥스 함수 구현하기__

In [ ]:
import numpy as np

a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a) #지수 함수
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [ ]:
sum_exp_a = np.sum(exp_a) #지수 함수의 합
print(sum_exp_a)

74.1221542101633


In [ ]:
y = exp_a / sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


In [ ]:
def softmax(a):
  exp_a = np.exp(a)
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a

  return y

### __3.5.2 소프트맥스 함수 구현 시 주의점__

In [ ]:
a = np.array([1010, 1000, 990])
print(np.exp(a) / np.sum(np.exp(a))) #소프트맥스 함수의 계산. 제대로 계산되지 않는다.

[nan nan nan]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


In [ ]:
c = np.max(a) # c = 1010 (최댓값)
print(a - c)

[  0 -10 -20]


In [ ]:
print(np.exp(a - c) / np.sum(np.exp(a - c)))

[9.99954600e-01 4.53978686e-05 2.06106005e-09]


In [ ]:
def softmax(a):
  c = np.max(a)
  exp_a = np.exp(a - c) # 오버플로 대책
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a

  return y

### __3.5.3 소프트맥스 함수의 특징__

In [ ]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)
print(np.sum(y))

[0.01821127 0.24519181 0.73659691]
1.0
